---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

p_auto_df <- read_csv("grouped_p_auto.csv")

######################### get mean and sd (or se) ######################### 
p_auto_df %>%
  group_by(autonomy, order) %>%
  get_summary_stats(p_auto, type = "mean_sd")


######################### NASA-TLX ######################### 
p <- ggplot(p_auto_df, aes(x=order, y=p_auto, fill=factor(interaction(order, auto_grouped)))) + 
  geom_dotplot(binaxis='y', stackdir='center', stackratio=1.5, dotsize=1.4) + 
  labs( x = "Order", y = "Perceived Autonomy", fill = "Autonomy Level") + theme_minimal() +
  stat_summary(fun.y = mean, geom="crossbar", colour="red", width=0.5, size=0.7) +
  scale_fill_manual(values=c("#0000CC", "#3399FF", "#006600", "#00CC00")) +
    theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 28, face = "bold"),
        axis.title.y = element_text(size = 28, face = "bold"),
        axis.text = element_text(size = 24),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 11),
        legend.position= "none") +
  facet_grid(. ~ auto_grouped, ) +
  theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 24, face = "bold"),
        strip.text.x = element_text(angle = 0, hjust = 0.5, size = 28, face = "bold"), legend.position = "none")
p


```

## Plots

```{r do plotting}

######################### cool box plot (courtesy of Sarah) ######################### 
ggplot(p_auto_df,aes(x=order,y=p_auto, fill=order))+geom_boxplot(aes(fill=order)) + labs( x = "Order", y = "p_auto", fill = "Order") +   theme_minimal() +
# stat_summary(fun = mean, geom = "point",size = 3, shape = 2, position = position_dodge(0.75), show.legend = FALSE) +
scale_fill_brewer(palette = "Set2") +
    theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 11),
        legend.position= "none") +
  facet_grid(. ~ autonomy) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(angle = 0, hjust = 0.5, size = 12), legend.position = "none")


######################### scatterplot ######################### 
ggplot(p_auto_df, aes(x=autonomy, y=p_auto)) + 
    geom_point()


```


## Check assumptions

```{r check assumptions}

######################### check for outliers ######################### 
p_auto_df %>%
  group_by(autonomy, order) %>%
  identify_outliers(p_auto)

######################### check normality #########################
ggqqplot(p_auto_df, "p_auto", ggtheme = theme_bw()) + facet_grid(autonomy ~ order)

######################### check variance homogeneity ######################### 
p_auto_df %>%
  group_by(autonomy) %>%
  levene_test(p_auto ~ order)

######################### check covariance homogeneity ######################### 
box_m(p_auto_df[, "p_auto", drop = FALSE], p_auto_df$order)

```


## Fit Model

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = p_auto_df, dv = p_auto, wid = pid, between = order, within = autonomy)
anova_p_auto <- get_anova_table(res.aov)
anova_p_auto

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
