---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

big_df <- read_csv("combined.csv", show_col_types = FALSE)

```

# scatterplot and save, and compute correlation
```{r correlation}

######################### scatterplot ######################### 
p <- ggscatter(big_df, x = "traj_err", y = "mdmt_ave",
          add = "reg.line",                                 # Add regression line
          conf.int = TRUE,                                  # Add confidence interval
          add.params = list(color = "blue",
                            fill = "lightgray"),
          xlab = "Trajectory Tracking Error", ylab = "Averaged MDMT"
          ) +
    theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 28, face = "bold"),
        axis.title.y = element_text(size = 28, face = "bold"),
        axis.text = element_text(size = 24),
        legend.title = element_text(size = 28),
        legend.text = element_text(size = 28),
        legend.position= "none")
  # stat_cor(method = "pearson", label.x = 1.5, label.y = 7.5)  # Add correlation coefficient
p
ggsave(file="perf_trust_corr.pdf", plot=p, width=10, height=6)


######################### correlation test ######################### 
res <- cor.test(big_df$traj_err, big_df$mdmt_ave, 
                    method = "pearson")
res


######################### correlation test ######################### 
res <- cor.test(big_df$traj_err, big_df$p_trust, 
                    method = "pearson")
res

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
