---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ggplot2)
library(jtools)
library(interactions)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

big_df <- read_csv("combined.csv", show_col_types = FALSE)


############################## fit a linear regression model ##############################
fit <- lm(traj_err ~ tlx_ave * autonomy, data = big_df)
summary(fit)

############################## interaction plot ##############################
p <- interact_plot(fit, pred = tlx_ave, modx = autonomy, 
              interval = TRUE, int.type = "confidence", int.width = .8,
              plot.points = TRUE,
              x.label="Cognitive Load", y.label="Trajectory Tracking Error", 
              modx.labels = c("low", "high")
              ) + 
  theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 20, face = "bold"),
        axis.title.y = element_text(size = 20, face = "bold"),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20))
p



```

```{r read csv}

############################## fit a linear regression model ##############################
fit <- lm(mdmt_ave ~ traj_err * autonomy, data = big_df)
summary(fit)

############################## interaction plot ##############################
p <- interact_plot(fit, pred = traj_err, modx = autonomy, 
              interval = TRUE, int.type = "confidence", int.width = .8,
              plot.points = TRUE,
              x.label="Trajectory Tracking Error", y.label="Trust", 
              modx.labels = c("low", "high")
              ) + 
  theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 20, face = "bold"),
        axis.title.y = element_text(size = 20, face = "bold"),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20))
p

```

```{r read csv}

############################## fit a linear regression model ##############################
fit <- lm(tlx_ave ~ traj_err * autonomy, data = big_df)
summary(fit)

############################## interaction plot ##############################
p <- interact_plot(fit, pred = traj_err, modx = autonomy, 
              interval = TRUE, int.type = "confidence", int.width = .8,
              plot.points = TRUE,
              x.label="Trajectory Tracking Error", y.label="Cognitive Load", 
              modx.labels = c("low", "high")
              ) + 
  theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 20, face = "bold"),
        axis.title.y = element_text(size = 20, face = "bold"),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20))
p

```


```{r read csv}

############################## fit a linear regression model ##############################
fit <- lm(tlx_ave ~ p_trust * autonomy, data = big_df)
summary(fit)

############################## interaction plot ##############################
p <- interact_plot(fit, pred = p_trust, modx = autonomy, 
              interval = TRUE, int.type = "confidence", int.width = .8,
              plot.points = TRUE,
              x.label="Trust", y.label="Cognitive Load", 
              modx.labels = c("low", "high")
              ) + 
  theme(plot.title = element_text(size = 15, face = "bold"),
        axis.title.x = element_text(size = 20, face = "bold"),
        axis.title.y = element_text(size = 20, face = "bold"),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20))
p

```

```{r read csv}

ggplot(big_df, aes(x = mdmt_ave, y = tlx_successful)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")


######################### correlation test ######################### 
res <- cor.test(big_df$tlx_successful, big_df$mdmt_ave, 
                    method = "pearson")
res

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
